### ISSUE TITLE
singularity 

### ISSUE THREAD

**Issue by JakubSido** [fpartl/metaenv#1]
Po aktivaci singularity se neprovolají definice ničeho. Tedy nefunguje například alias definovaný v .metaenv_user_conf

```bash
alias server="~/tools/vscode/code tunnel --log trace --verbose"
alias ensi="singularity shell --nv /cvmfs/singularity.metacentrum.cz/NGC/PyTorch\:21.03-py3.SIF"
alias enco="encuba"
```

**Comment by fpartl** [comment]
ad 1: #8 added `sinshell` command which propagates `vscode-server` alias into Singularity shell. 
ad 2: seriously? :smile: 
ad 3: #8 also renamed `encuba` to `enco` so watch out!

Enjoy :sunglasses:
