### ISSUE TITLE
V singularitě nefunguje alias vscode-server

### ISSUE THREAD

**Issue by JakubSido** [fpartl/metaenv#15]
V singularitě nefunguje alias vscode-server

**Comment by fpartl** [comment]
Máš pravdu, obecně nefungoval. Fungoval jenom na oko, když byla interaktivní sešna spuštěna na stejném stroji, na kterém byla plánována (těžká magie)... V #17 jsem export aliasu `vscode-server` z příkazu `sinshell` smazal a místo toho jej jenom vypisuji. To znamená, že pokud chceš `vscode-server` používat, tak stačí si ten příkaz jenom zkopírovat a spustit. Jenom se to prostě neděje automaticky.
