### ISSUE TITLE
nefunkčni instalace vscode cli

### ISSUE THREAD

**Issue by JakubSido** [fpartl/metaenv#18]
Nefunguje instalace vscode server -- 

![image](https://github.com/fpartl/metaenv/assets/49715384/6024d5e5-061a-420a-a45a-3cf0097e7700)

**Comment by fpartl** [comment]
Jasný, vidím to. Když přeskočíš instalaci nového `.metaenv_user_conf` souboru, tak nemá se nemá kam doplňovat do `PATH`.

Opraveno v #19. Když instalaci nového `.metaenv_user_conf` souboru přeskočíš, tak se do něj VSCode stejně přidá. Tedy tam může být vícekrát, což by ovšem nemuselo vadit. 

![obrazek](https://github.com/fpartl/metaenv/assets/22639820/773dbd51-8751-418d-ad37-8121ce0a49a7)
